### ISSUE TITLE
RWD article image isn't converting at break points

### ISSUE THREAD

**Issue by m1ca** [alistapart/AListApart#384]
The image at http://alistapart.com/article/responsive-web-design isn't changing over to the stacked versions when the window narrows.

**Comment by zeldman** [comment]
Dang! Thanks for noticing, Mica.



…………………………………

studio.zeldman <http://studio.zeldman.com>
148 Madison Avenue, Suite 600
New York, NY 10016
917-746-4838

An Event Apart <http://aneventapart.com/subscribe> | A List Apart
<http://alistapart.com/> | A Book Apart <https://abookapart.com>
Big Web Show
<https://itunes.apple.com/us/podcast/the-big-web-show/id370445683?mt=2> |
zeldman.com | @zeldman <https://twitter.com/zeldman>

**Comment by michaelspellacy** [comment]
Looks like the issue related to the first `<source>` element within `<picture>`. 

Currently:

```
<source srcset="http://alistapart.com//d/_made/d/misc-images/rwd-1_2577_1165_61.jpg">
```
Should probably be:

```
<source srcset="http://alistapart.com//d/_made/d/misc-images/rwd-1_2577_1165_61.jpg" media="(min-width: 2577px)">
```

**Comment by michaelspellacy** [comment]
Does that behavior seem a little peculiar to either of you? It seems to me it should fail more gracefully and simply not load the source without a `media` attribute. Wonder if it a bug.

**Comment by michellekondou** [comment]
@michaelspellacy it's a backend issue, thank you for your feedback! 
@m1ca @zeldman I'm working on it. I'll push the corrected version in a little while.

**Comment by michellekondou** [comment]
@m1ca @zeldman Ok this has been corrected! This happened earlier this year when we made the transition to the picture tag, and it wasn't working correctly in conjuction with the EE matrix plugin. We hadn't noticed because the responsive web design article is the only one using this particular field.

**Comment by zeldman** [comment]
Thanks, MK!



…………………………………

studio.zeldman <http://studio.zeldman.com>
148 Madison Avenue, Suite 600
New York, NY 10016
917-746-4838

An Event Apart <http://aneventapart.com/subscribe> | A List Apart
<http://alistapart.com/> | A Book Apart <https://abookapart.com>
Big Web Show
<https://itunes.apple.com/us/podcast/the-big-web-show/id370445683?mt=2> |
zeldman.com | @zeldman <https://twitter.com/zeldman>

**Comment by michaelspellacy** [comment]
Cool. Happy to help! What I wondering, was, is this a bigger problem with the picture element itself? It seems like missing one media attribute is a recipe for trouble, no? Rather than still continue to use the other sources in those breakpoints, which have a proper media attribute, the entire thing fails and only presents user with the fallback image. I checked on a couple of other browser and this behavior is consistent, but it just seems So odd to me that it should behave that way. Oh, well. Maybe I'll do a little digging on it. Glad all well now!
